package db

import (
	"context"
	"database/sql"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestRewrite(t *testing.T) {
	for in, want := range map[string]string{
		`SELECT id FROM subs WHERE login = ? COLLATE NOCASE AND id != ?`:   `SELECT id FROM subs WHERE lower(login) = lower($1) AND id != $2`,
		`SELECT id FROM accounts WHERE username = ?`:                       `SELECT id FROM accounts WHERE lower(username) = lower($1)`,
		`SELECT a.id FROM accounts a WHERE a.username = ? AND s.ip = ?`:    `SELECT a.id FROM accounts a WHERE lower(a.username) = lower($1) AND s.ip = $2`,
		`SELECT * FROM certs ORDER BY name COLLATE NOCASE, id`:             `SELECT * FROM certs ORDER BY lower(name), id`,
		`SELECT GROUP_CONCAT(DISTINCT server_id), GROUP_CONCAT(x) FROM t`:  `SELECT string_agg(DISTINCT CAST(server_id AS TEXT), ','), string_agg(CAST(x AS TEXT), ',') FROM t`,
		`SELECT 1 WHERE CAST(json_extract(data, '$.cert') AS INTEGER) = ?`: `SELECT 1 WHERE CAST((meridian_json(data) ->> 'cert') AS BIGINT) = $1`,
		`SELECT value FROM json_each(?) WHERE host LIKE ?`:                 `SELECT value FROM jsonb_array_elements_text(CAST($1 AS jsonb)) WHERE host ILIKE $2`,
		`SELECT '?' || ?, "a?" FROM t -- what?` + "\n" + `WHERE x = ?`:     `SELECT '?' || $1, "a?" FROM t -- what?` + "\n" + `WHERE x = $2`,
		`INSERT INTO traffic_daily (day, sub_id, node_id, up, down) VALUES (?, ?, ?, ?, ?) ON CONFLICT(day, sub_id, node_id) DO UPDATE SET up = up + excluded.up, down = down + excluded.down`: `INSERT INTO traffic_daily (day, sub_id, node_id, up, down) VALUES ($1, $2, $3, $4, $5) ON CONFLICT(day, sub_id, node_id) DO UPDATE SET up = traffic_daily.up + excluded.up, down = traffic_daily.down + excluded.down`,
		`INSERT INTO id_floor (name, last) VALUES ('ext_nodes', ?) ON CONFLICT(name) DO UPDATE SET last = MAX(last, excluded.last)`:                                                            `INSERT INTO id_floor (name, last) VALUES ('ext_nodes', $1) ON CONFLICT(name) DO UPDATE SET last = GREATEST(id_floor.last, excluded.last)`,
		`INSERT INTO ip_log (day, first_seen) VALUES (?, ?) ON CONFLICT(day) DO UPDATE SET first_seen = MIN(first_seen, excluded.first_seen), conns = conns + 1`:                               `INSERT INTO ip_log (day, first_seen) VALUES ($1, $2) ON CONFLICT(day) DO UPDATE SET first_seen = LEAST(ip_log.first_seen, excluded.first_seen), conns = ip_log.conns + 1`,
	} {
		if got := rewrite(in).sql; got != want {
			t.Errorf("\n in: %s\ngot: %s\nwant: %s", in, got, want)
		}
	}
	if !rewrite(`INSERT INTO servers (name) VALUES (?)`).returning || rewrite(`INSERT INTO settings (key, value) VALUES (?, ?)`).returning ||
		rewrite("-- copy\nINSERT INTO servers (name) VALUES (?)").returning {
		t.Error("which inserts return their new id")
	}
}

// TestPostgresSchema: SQLite's schema, read back, makes PostgreSQL's - every table, its keys, the
// case-insensitive and partial indexes, the foreign keys and the id floor's triggers.
func TestPostgresSchema(t *testing.T) {
	s, err := pgSchema()
	if err != nil {
		t.Fatal(err)
	}
	ddl := strings.Join(s.ddl, ";\n")
	for _, want := range []string{
		"CREATE TABLE servers (\n  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
		"CREATE UNIQUE INDEX accounts_username_key ON accounts (lower(username))",
		"CREATE UNIQUE INDEX subs_login ON subs (lower(login)) WHERE login != ''",
		"CHECK (role IN ('owner','admin'))",
		"ALTER TABLE nodes ADD CONSTRAINT nodes_server_id_fkey FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE",
		"PRIMARY KEY (monitor_id, server_id, ts)",
		"CREATE TRIGGER subs_id_floor AFTER DELETE ON subs",
		"cpu DOUBLE PRECISION NOT NULL DEFAULT 0",
		"PRIMARY KEY (key)",
	} {
		if !strings.Contains(ddl, want) {
			t.Errorf("the schema lacks %q", want)
		}
	}
	// parents come first
	seen := map[string]bool{}
	for _, tb := range s.tables {
		for _, fk := range tb.FKs {
			if !seen[fk.Parent] && fk.Parent != tb.Name {
				t.Errorf("%s comes before %s, which it refers to", tb.Name, fk.Parent)
			}
		}
		seen[tb.Name] = true
	}
	if !idTable("servers") || idTable("settings") || idTable("server_metrics") {
		t.Error("which tables count their ids")
	}
}

// TestPostgresRoundTrip copies a SQLite database into PostgreSQL and back (MERIDIAN_TEST_PG: a
// PostgreSQL URL whose role may create databases).
func TestPostgresRoundTrip(t *testing.T) {
	base := os.Getenv("MERIDIAN_TEST_PG")
	if base == "" {
		t.Skip("MERIDIAN_TEST_PG is not set")
	}
	ctx := context.Background()
	dir := t.TempDir()
	src, err := Open(filepath.Join(dir, "a.db"))
	if err != nil {
		t.Fatal(err)
	}
	defer src.Close()
	for _, q := range []string{
		`INSERT INTO accounts (id, username, display_name, role, password_hash, created_at) VALUES (1, 'Admin', 'Owner', 'owner', 'x', 1)`,
		`INSERT INTO servers (id, account_id, name, secret, created_at, lat) VALUES (7, 1, 'Tokyo ☀', 's', 2, 35.68)`,
		`INSERT INTO nodes (id, server_id, kind, port, settings, created_at, updated_at) VALUES (40, 7, 'vless', 443, '{"a":1}', 3, 3)`,
		`INSERT INTO server_metrics (server_id, ts, cpu, mem_used) VALUES (7, 60, 12.5, 9007199254740993)`,
		`INSERT INTO settings (key, value) VALUES ('panel', '{"site_title":"x"}')`,
		`INSERT INTO id_floor (name, last) VALUES ('nodes', 55)`,
	} {
		if _, err := src.Exec(q); err != nil {
			t.Fatalf("%s: %v", q, err)
		}
	}
	// a row whose parent is gone (SQLite kept such rows while its checks were off)
	conn, err := src.Conn(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := conn.ExecContext(ctx, `PRAGMA foreign_keys = OFF`); err != nil {
		t.Fatal(err)
	}
	if _, err := conn.ExecContext(ctx, `INSERT INTO forwards (id, server_id, listen_port, target, created_at, updated_at) VALUES (3, 99, 1000, 'x:1', 1, 1)`); err != nil {
		t.Fatal(err)
	}
	conn.ExecContext(ctx, `PRAGMA foreign_keys = ON`)
	conn.Close()
	u, _ := url.Parse(base)
	admin, err := sql.Open("pgx", base)
	if err != nil {
		t.Fatal(err)
	}
	defer admin.Close()
	name := fmt.Sprintf("mt_rt_%d", time.Now().UnixNano())
	if _, err := admin.Exec(`CREATE DATABASE ` + name); err != nil {
		t.Fatal(err)
	}
	defer admin.Exec(`DROP DATABASE IF EXISTS ` + name + ` WITH (FORCE)`)
	u.Path = "/" + name
	pg, err := OpenPostgres(u.String())
	if err != nil {
		t.Fatal(err)
	}
	defer pg.Close()
	orphans := 0
	if err := Copy(ctx, src, pg, func(_ string, _, o int) { orphans += o }); err != nil {
		t.Fatal(err)
	}
	if orphans != 1 {
		t.Errorf("%d rows left behind, want the forward of a removed server", orphans)
	}
	var who string
	var mem int64
	var lat float64
	pg.QueryRow(`SELECT username FROM accounts WHERE username = ?`, "admin").Scan(&who)
	pg.QueryRow(`SELECT mem_used FROM server_metrics WHERE server_id = 7`).Scan(&mem)
	pg.QueryRow(`SELECT lat FROM servers WHERE id = 7`).Scan(&lat)
	if who != "Admin" || mem != 9007199254740993 || lat != 35.68 {
		t.Errorf("in PostgreSQL: %q %d %v", who, mem, lat)
	}
	// new rows count on from the copied ids; deleted nodes raise the floor
	res, err := pg.Exec(`INSERT INTO servers (account_id, name, secret, created_at) VALUES (1, 'Osaka', 's', 4)`)
	if err != nil {
		t.Fatal(err)
	}
	if id, _ := res.LastInsertId(); id != 8 {
		t.Errorf("a new server's id: %d", id)
	}
	if _, err := pg.Exec(`DELETE FROM nodes WHERE id = 40`); err != nil {
		t.Fatal(err)
	}
	var next int64
	pg.QueryRow(`SELECT ` + NextID("nodes")).Scan(&next)
	if next != 56 {
		t.Errorf("the next node id: %d, want 56 (the floor)", next)
	}
	// and back
	back := filepath.Join(dir, "b.db")
	if err := pg.Snapshot(ctx, back); err != nil {
		t.Fatal(err)
	}
	b, err := Open(back)
	if err != nil {
		t.Fatal(err)
	}
	defer b.Close()
	var n int
	b.QueryRow(`SELECT COUNT(*) FROM servers`).Scan(&n)
	var title string
	b.QueryRow(`SELECT name FROM servers WHERE id = 7`).Scan(&title)
	if n != 2 || title != "Tokyo ☀" {
		t.Errorf("back in SQLite: %d servers, %q", n, title)
	}
}
